spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: abc123
mybatis:
  config-location: classpath:mybatis.xml    
